linters:
  enable-all: true
  disable:
    - exportloopref # Deprecated
    - exhaustruct # Too noisy
    - mnd # Too noisy
linters-settings:
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
