failure-threshold: error
strict-labels: true
label-schema:
  org.opencontainers.image.authors: text
  org.opencontainers.image.title: text
  org.opencontainers.image.url: url
  org.opencontainers.image.documentation: url
  org.opencontainers.image.source: url
  org.opencontainers.image.licenses: text
trustedRegistries:
  - index.docker.io
  - gcr.io
