name: recorder
services:
  postgresql:
    image: index.docker.io/postgres:16.3@sha256:d0f363f8366fbc3f52d172c6e76bc27151c3d643b870e1062b4e8bfe65baf609
    init: true
    restart: unless-stopped
    container_name: postgresql
    hostname: postgresql
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
    networks:
      - recorder-network
    ports:
      - $POSTGRES_PORT:$POSTGRES_PORT
    volumes:
      - type: bind
        read_only: true
        source: ../../certs/postgresql.crt.pem
        target: /var/lib/postgresql/server.crt
      - type: bind
        read_only: true
        source: ../../certs/postgresql.key.pem
        target: /var/lib/postgresql/server.key
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    secrets:
      - postgres_password
  migrator:
    build:
      context: ../..
      dockerfile: images/migrator.Dockerfile
    init: true
    container_name: migrator
    hostname: migrator
    environment:
      POSTGRES_HOST: $POSTGRES_HOST
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD_PATH: /run/secrets/postgres_password
      MIGRATIONS_PATH: $MIGRATIONS_PATH
    volumes:
      - ../../sql:$MIGRATIONS_PATH:ro
      - type: bind
        read_only: true
        source: ../../certs/migrator.crt.pem
        target: /etc/recorder/migrator.crt.pem
      - type: bind
        read_only: true
        source: ../../certs/migrator.key.pem
        target: /etc/recorder/migrator.key.pem
    networks:
      - recorder-network
    secrets:
      - postgres_password
    depends_on:
      postgresql:
        condition: service_healthy
networks:
  recorder-network:
    driver: bridge
    name: recorder-network
secrets:
  postgres_password:
    environment: POSTGRES_PASSWORD
